declare function eqRGBVal(val1: string, val2: string): boolean;
declare function eqHEXVal(val1: string, val2: string): boolean;
declare function eqStringColorVal(val1: string, val2: string): boolean;
declare function eqRGBNHEX(val1: string, val2: string): boolean;
declare function eqStringColorValNOther(val1: string, val2: string): boolean;
export declare function isColorVal(val: string): boolean;
export declare function isStringColorVal(val: string): boolean;
export declare function stringColor2RGB(val: string): string;
export declare function stringColor2HEX(val: string): string;
export declare function isRGBVal(val: string): boolean;
export declare function isHEXVal(val: string): boolean;
export declare function isShortHEXVal(val: string): boolean;
export declare function isLongHEXVal(val: string): boolean;
export declare function RGB2HEX(RGBVal: string): string;
export declare function HEX2RGB(HEXVal: string): string;
export declare function shortHEXVal2LongHEXVal(HEXVal: string): string;
export declare function eqColorVal(val1: string, val2: string): boolean;
export declare function assignCssObj(base: Object<any>, obj: Object<any>): Object<any>;
export declare function getCSSStyle(dom: HTMLElement): Object<any>;
